# Generated by Django 5.1.1 on 2024-09-29 14:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='category_technology',
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, choices=[('option1', 'Website Design'), ('option2', 'Product Development'), ('option3', 'Graphics Design')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
