# Generated by Django 5.1.1 on 2024-09-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_project_category_technology_project_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, choices=[('Website Design', 'option1'), ('Product Development', 'option2'), ('Graphics Design', 'option3')], max_length=255, null=True),
        ),
    ]
