# Generated by Django 5.1.1 on 2024-10-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_search_alter_project_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, choices=[('Website Design', 'Website Design'), ('Product Development', 'Product Development'), ('Mobile App Development', 'Mobile App Development'), ('Mobile App and Web Maintenance', 'Mobile App and Web Maintenance')], default='Website Design', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default='Such beautiful Projects!'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FileField(blank=True, default='hj.jpg', upload_to=''),
        ),
    ]
